global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "dear-comrade-batch-integration-zero-to-hero"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "localhost:8080"
