global:
  scrape_interval: 1m
  scrape_timeout: 1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'job-grafana-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:8008']
        labels:
          application: 'grafana-prometheus'