version: "3.1"
services:
  oracle:
    image: gvenzl/oracle-free:latest
    environment:
      - "ORACLE_RANDOM_PASSWORD: true"
      - "APP_USER: dear"
      - "APP_USER_PASSWORD: comrade"
    ports:
      - 1521:1521
    options: >-
      --health-cmd healthcheck.sh
      --health-interval 10s
      --health-timeout 5s
      --health-retries 10
